import './globals.scss'

import ReactLenis from 'lenis/react'
import type {Metadata} from 'next'
import {Chakra_Petch, Montserrat} from 'next/font/google'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

const chakraPetch = Chakra_Petch({
  subsets: ['latin'],
  variable: '--font-chakraPetch',
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Portfolio - Trung Nguyen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${montserrat.variable} ${chakraPetch.variable} antialiased`}>
        <ReactLenis root>{children}</ReactLenis>
      </body>
    </html>
  )
}
